spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
    client:
        registerWithEureka: false  #false:不作为一个客户端注册到注册中心
        fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
        serviceUrl:
          defaultZone: http://192.168.86.1:8761/eureka/



